sudo: false
language: node_js
node_js: stable
cache: npm
branches:
  only:
    - main # build master branch only
cache:
    directories:
        - node_modules
install:
  - npm install   #安装hexo及插件
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  on:
    branch: main
  local-dir: public
